//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Add_Browse {
            get {
                return ResourceManager.GetString("Add_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Add_Completed {
            get {
                return ResourceManager.GetString("Add_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Add_Image {
            get {
                return ResourceManager.GetString("Add_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Add_Link {
            get {
                return ResourceManager.GetString("Add_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Add_Name {
            get {
                return ResourceManager.GetString("Add_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Add_Site {
            get {
                return ResourceManager.GetString("Add_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Add_Tags {
            get {
                return ResourceManager.GetString("Add_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add_Title {
            get {
                return ResourceManager.GetString("Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Add_Unknown {
            get {
                return ResourceManager.GetString("Add_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update date.
        /// </summary>
        public static string Add_UpdateDate {
            get {
                return ResourceManager.GetString("Add_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Add_Version {
            get {
                return ResourceManager.GetString("Add_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new....
        /// </summary>
        public static string AddNewSort {
            get {
                return ResourceManager.GetString("AddNewSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing.
        /// </summary>
        public static string Closing {
            get {
                return ResourceManager.GetString("Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        public static string Edit_Title {
            get {
                return ResourceManager.GetString("Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude by: .
        /// </summary>
        public static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag {
            get {
                object obj = ResourceManager.GetObject("flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add .
        /// </summary>
        public static string Message_Add_Filter_Begin {
            get {
                return ResourceManager.GetString("Message_Add_Filter_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  as a filter?.
        /// </summary>
        public static string Message_Add_Filter_End {
            get {
                return ResourceManager.GetString("Message_Add_Filter_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This filter .
        /// </summary>
        public static string Message_Add_FilterExist_Begin {
            get {
                return ResourceManager.GetString("Message_Add_FilterExist_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  already exist!.
        /// </summary>
        public static string Message_Add_FilterExist_End {
            get {
                return ResourceManager.GetString("Message_Add_FilterExist_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is already completed..
        /// </summary>
        public static string Message_Completed_Begin {
            get {
                return ResourceManager.GetString("Message_Completed_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        public static string Message_Completed_End {
            get {
                return ResourceManager.GetString("Message_Completed_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete .
        /// </summary>
        public static string Message_Delete_Item_Begin {
            get {
                return ResourceManager.GetString("Message_Delete_Item_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ?.
        /// </summary>
        public static string Message_Delete_Item_End {
            get {
                return ResourceManager.GetString("Message_Delete_Item_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete filter &quot;.
        /// </summary>
        public static string Message_DeleteFilter_Begin {
            get {
                return ResourceManager.GetString("Message_DeleteFilter_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; ?.
        /// </summary>
        public static string Message_DeleteFilter_End {
            get {
                return ResourceManager.GetString("Message_DeleteFilter_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password field cannot be empty!.
        /// </summary>
        public static string Message_Empty_User_Password {
            get {
                return ResourceManager.GetString("Message_Empty_User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close this program?.
        /// </summary>
        public static string Message_Exit {
            get {
                return ResourceManager.GetString("Message_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password is incorrect!.
        /// </summary>
        public static string Message_Incorect_User_Password {
            get {
                return ResourceManager.GetString("Message_Incorect_User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must fill all the fields before continue!.
        /// </summary>
        public static string Message_Invalid_Parameters {
            get {
                return ResourceManager.GetString("Message_Invalid_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates were found..
        /// </summary>
        public static string Message_NoUpdates {
            get {
                return ResourceManager.GetString("Message_NoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all datas?.
        /// </summary>
        public static string Message_ResetData {
            get {
                return ResourceManager.GetString("Message_ResetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all settings?.
        /// </summary>
        public static string Message_ResetSettings {
            get {
                return ResourceManager.GetString("Message_ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for updates...
        ///This may take several minutes.
        ///Please don&apos;t close this program!.
        /// </summary>
        public static string Message_Updating {
            get {
                return ResourceManager.GetString("Message_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; None &gt;.
        /// </summary>
        public static string NoneSelected {
            get {
                return ResourceManager.GetString("NoneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has been closed..
        /// </summary>
        public static string Notificaion_Close {
            get {
                return ResourceManager.GetString("Notificaion_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Notification_Menu_Close {
            get {
                return ResourceManager.GetString("Notification_Menu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Notification_Menu_Show {
            get {
                return ResourceManager.GetString("Notification_Menu_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has been minimized to tray..
        /// </summary>
        public static string Notification_Minimization {
            get {
                return ResourceManager.GetString("Notification_Minimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all data.
        /// </summary>
        public static string ResetData_Button {
            get {
                return ResourceManager.GetString("ResetData_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings.
        /// </summary>
        public static string ResetSettings_Button {
            get {
                return ResourceManager.GetString("ResetSettings_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save_Button {
            get {
                return ResourceManager.GetString("Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusion list from searching of updates: .
        /// </summary>
        public static string Settings_General_ExclusionList {
            get {
                return ResourceManager.GetString("Settings_General_ExclusionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        public static string Settings_General_Language {
            get {
                return ResourceManager.GetString("Settings_General_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show message when going to system tray .
        /// </summary>
        public static string Settings_General_MessageSystemTray {
            get {
                return ResourceManager.GetString("Settings_General_MessageSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to system tray .
        /// </summary>
        public static string Settings_General_MinimizationMode {
            get {
                return ResourceManager.GetString("Settings_General_MinimizationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top .
        /// </summary>
        public static string Settings_General_TopmostMode {
            get {
                return ResourceManager.GetString("Settings_General_TopmostMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        public static string Settings_Visual {
            get {
                return ResourceManager.GetString("Settings_Visual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by: .
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
